### ISSUE TITLE
Load all JUnit test reports, not just the first one

### ISSUE THREAD

**Issue by tsantalis** [GaelGirodon/ci-badges-action#2]
@GaelGirodon 

My project has multiple test reports
https://github.com/tsantalis/RefactoringMiner/actions/runs/9143815119/job/25141202337

I added your action in the project's workflow
and it loads only the first one

> Load JUnit report '/home/runner/work/RefactoringMiner/RefactoringMiner/build/test-results/test/TEST-org.kohsuke.github.GHRepositoryWrapperTest.xml'
> Loaded 1 JUnit report(s)

Is it possible to load all test reports, and save in the json, the total number of passed/failed/skipped tests?

Thank you,
Nikos

**Comment by GaelGirodon** [comment]
It's working [as intended](https://github.com/GaelGirodon/ci-badges-action/blob/1a45c9031e1fff105e3b10b4c5f3d49908d0d2f8/src/reports/junit.js#L37), the action only loads the first valid report file (closest to the project root directory) for each supported format, but I admit this behavior may not be ideal for all use cases.

I mainly considered Node.js/Go tools that seem to generate a single aggregated report file most of the time, but that's obviously not the case for Maven/Gradle projects.

Parsing all JUnit report files may suit your use case, but not others, e.g. this will break for projects having both aggregated and detailed report files.

In a future release, I'll try to :

- Find a balanced solution
- Improve the documentation to be more transparent about this behavior

I could add configuration parameters but I'm trying to make this action as configuration-less as possible to:

- Make it simple to use
- Avoid defining parameters that might need to change in the future and might not be backward compatible
- Avoid having to name things 😅

In the meantime, as a workaround, you can try to:

- Find a Gradle plugin to generate an aggregated report file, this file will be the one that is loaded if it is located higher than detailed reports in the file hierarchy
- Generate this file by yourself, e.g. with a simple shell command like `find ./path/to/reports/ -name 'TEST-*.xml' -exec cat {} > TEST-results.xml \;`

I'm open to ideas & suggestions if you have any! I let this issue opened as this feature request is justified and I'd want to find an appropriate solution.

**Comment by tsantalis** [comment]
@GaelGirodon 
Thank you for your detailed analysis.

I think it would be nice to have an optional parameter to enable loading all test reports and aggregate the results.
Without specifying this parameter, the default behavior will be the current one.

In Java projects, I would say it is the most common to have multiple test reports.

The change on your side is very simple.
You just need to put the [break](https://github.com/GaelGirodon/ci-badges-action/blob/1a45c9031e1fff105e3b10b4c5f3d49908d0d2f8/src/reports/junit.js#L37) statement into an `if` controlled by this parameter.

Actually, I don't see any valid reason to have this `break` in your code.
Without this break, the code as is, aggregates all test results.
So, the easiest solution is to just delete this `break` statement.

**Comment by GaelGirodon** [comment]
If I only make the `break` statement conditional, it will create a badge per test report file and only the last one will be uploaded as all will have the same name, so that's not the desired behavior.

I've done more research about multiple test runners and none of them seem to produce both a single aggregated report and multiple detailed ones. But nearly all of them may produce multiple report files, by default (e.g. Maven Surefire/Failsafe or Gradle), or in case of sharding. Merging multiple report files seems to always require an additional step, that is most of the time unnecessary because reporting tools generally support multiple input files (e.g. [GitLab CI](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportsjunit), Maven Surefire Report Plugin, the GitHub action you're using, etc.).

So I'm going to modify the action to make it stick to the most common behavior, i.e., load all available test reports. The new version will be released soon, maybe this week, you can preview [changes](https://github.com/GaelGirodon/ci-badges-action/compare/1.3.0...main) to be released on the `main` branch.

**Comment by tsantalis** [comment]
@GaelGirodon Thank you very much!

**Comment by GaelGirodon** [comment]
The [v1.4.0](https://github.com/marketplace/actions/ci-badges?version=v1.4.0) has just been released 🎉

@tsantalis Could you please check in your project if the issue is resolved?

**Comment by tsantalis** [comment]
@GaelGirodon 
I just generated the gist with your new release
https://gist.github.com/tsantalis/19fb416d06d1b4d40820e0209540f6c0/revisions

It shows a total of 1728 tests passing.
The correct value is 1718 tests passing + 10 skipped.
https://github.com/tsantalis/RefactoringMiner/actions/runs/9194068100/job/25297450738

I guess the skipped tests are counted as passing.

Anyways, it is far better than before! Thank you for your help.

**Comment by GaelGirodon** [comment]
Thanks for the test!

This is the expected behavior, skipped tests are indeed currently counted as passed tests.

I guess I already have another feature to support for the next release 🙂
Something like this ⬇️?

![0 passed](https://img.shields.io/badge/tests-0%20passed-lightgrey)
![0 passed, 1 skipped](https://img.shields.io/badge/tests-0%20passed%2C%201%20skipped-lightgrey)
![5 passed](https://img.shields.io/badge/tests-5%20passed-brightgreen)
![4 passed, 1 skipped](https://img.shields.io/badge/tests-4%20passed%2C%201%20skipped-brightgreen)
![4 passed, 1 failed](https://img.shields.io/badge/tests-4%20passed%2C%201%20failed-red)
![3 passed, 1 failed, 1 skipped](https://img.shields.io/badge/tests-3%20passed%2C%201%20failed%2C%201%20skipped-red)

**Comment by GaelGirodon** [comment]
The [v1.5.0](https://github.com/marketplace/actions/ci-badges?version=v1.5.0) has just been released 🎉

Skipped tests should now be counted and displayed separately, no change is required in the action usage:

![tests](https://img.shields.io/endpoint?url=https%3A%2F%2Fgist.githubusercontent.com%2FGaelGirodon%2F715c62717519f634185af0ebde234992%2Fraw%2Frepo-junit-tests.json)

Thanks @tsantalis for contributing to the improvement of this action through these feature requests and tests on your project!

**Comment by tsantalis** [comment]
@GaelGirodon 
I have to thank you for your awesome support.

I confirm it works
![image](https://github.com/GaelGirodon/ci-badges-action/assets/1483516/7cf33ca7-75ed-445d-a9bc-a6969a30ea74)
